version: 2
jobs:
  FIRSTJOB:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"
  SECONDJOB:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world again"
